services:
  db_analyst:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'arqui'
      MYSQL_USER: 'trio-arqui'
      MYSQL_PASSWORD: 'prueba123'
      MYSQL_ROOT_PASSWORD: 'prueba123'
    ports:
      - '3306:3306'
    volumes:
      - analyst-db:/var/lib/mysql

  db_products:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'arqui'
      MYSQL_USER: 'trio-arqui'
      MYSQL_PASSWORD: 'prueba123'
      MYSQL_ROOT_PASSWORD: 'prueba123'
    ports:
      - '3307:3306'
    volumes:
      - products-db:/var/lib/mysql
  
  store_component:
    build: backAnalyst/.
    restart: always
    volumes:
      - ./backAnalyst/:/code
    ports:
      - "8000:8000"
    depends_on:
      - db_analyst
      - mosquitto

  stock_component:
    build: backProducts/.
    restart: always
    volumes:
      - ./backProducts/:/code
    ports:
      - "8001:8000"
    depends_on:
      - db_products
      - mosquitto

  mosquitto:
    image: eclipse-mosquitto
    restart: always
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
  
  front_analyst:
    build:
      context: Front-TallerArqui/FrontAnalyst/.
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
  
  front_product:
    build:
      context: Front-TallerArqui/frontProducts/.
      dockerfile: Dockerfile
    ports:
      - "3000:3000"


volumes:
  analyst-db:
  products-db:
